class Planet
  include Mongoid::Document

  field :name, type: String
  field :x, type: Float
  field :y, type: Float
  field :url, type: String
  field :claimed_by, type: String
  field :claimed_name, type: String
  field :rowid, type: String
  field :pl_hostname, type: String
  field :pl_letter, type: String
  field :pl_discmethod, type: String
  field :pl_pnum, type: String
  field :pl_orbper, type: String
  field :pl_orbpererr1, type: String
  field :pl_orbpererr2, type: String
  field :pl_orbperlim, type: String
  field :pl_orbeccen, type: String
  field :pl_orbeccenerr1, type: String
  field :pl_orbeccenerr2, type: String
  field :pl_orbeccenlim, type: String
  field :pl_massj, type: String
  field :pl_massjerr1, type: String
  field :pl_massjerr2, type: String
  field :pl_massjlim, type: String
  field :pl_radj, type: String
  field :pl_radjerr1, type: String
  field :pl_radjerr2, type: String
  field :pl_radjlim, type: String
  field :pl_dens, type: String
  field :pl_denserr1, type: String
  field :pl_denserr2, type: String
  field :pl_denslim, type: String
  field :pl_orbincl, type: String
  field :pl_orbinclerr1, type: String
  field :pl_orbinclerr2, type: String
  field :pl_orbincllim, type: String
  field :ra_str, type: String
  field :ra, type: String
  field :dec_str, type: String
  field :dec, type: String
  field :st_dist, type: String
  field :st_disterr1, type: String
  field :st_disterr2, type: String
  field :st_distlim, type: String
  field :st_teff, type: String
  field :st_tefferr, type: String
  field :st_tefflim, type: String
  field :st_teffblend, type: String
  field :st_mass, type: String
  field :st_masserr, type: String
  field :st_masslim, type: String
  field :st_massblend, type: String
  field :st_rad, type: String
  field :st_raderr, type: String
  field :st_radlim, type: String
  field :st_radblend, type: String
  field :hd_name, type: String
  field :hip_name, type: String
  field :pl_name, type: String
  field :pl_tranflag, type: String
  field :pl_rvflag, type: String
  field :pl_imgflag, type: String
  field :pl_astflag, type: String
  field :pl_omflag, type: String
  field :pl_cbflag, type: String
  field :pl_masse, type: String
  field :pl_masseerr1, type: String
  field :pl_masseerr2, type: String
  field :pl_masselim, type: String
  field :pl_rade, type: String
  field :pl_radeerr1, type: String
  field :pl_radeerr2, type: String
  field :pl_radelim, type: String
  field :pl_trandur, type: String
  field :pl_trandurerr1, type: String
  field :pl_trandurerr2, type: String
  field :pl_trandurlim, type: String
  field :pl_disc, type: String
  field :pl_status, type: String
  field :pl_mnum, type: String
  field :pl_pelink, type: String
  field :pl_edelink, type: String
  field :st_plx, type: String
  field :st_plxerr, type: String
  field :st_plxlim, type: String
  field :st_plxblend, type: String
  field :st_pmra, type: String
  field :st_pmraerr, type: String
  field :st_pmralim, type: String
  field :st_pmdec, type: String
  field :st_pmdecerr, type: String
  field :st_pmdeclim, type: String
  field :st_sp, type: String
  field :st_spstr, type: String
  field :st_sperr, type: String
  field :st_splim, type: String
  field :st_spblend, type: String

end
